# Generated by Django 5.2.5 on 2025-09-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationitem',
            name='format',
            field=models.CharField(blank=True, choices=[('markdown', 'Markdown')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentationitem',
            name='role',
            field=models.CharField(blank=True, choices=[('readme', 'Readme')], max_length=100, null=True),
        ),
    ]
