# Generated by Django 5.2.5 on 2025-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentationitem_format_documentationitem_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationitem',
            name='format',
            field=models.CharField(blank=True, choices=[('markdown', 'Markdown'), ('plaintext', 'Plaintext')], max_length=100, null=True),
        ),
    ]
