# Generated by Django 5.2.5 on 2025-09-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_documentationitem_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationitem',
            name='role',
            field=models.CharField(blank=True, choices=[('readme', 'Readme'), ('license', 'License'), ('rfc', 'Rfc')], max_length=100, null=True),
        ),
    ]
