# Generated by Django 5.2.5 on 2025-11-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_documentationitem_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationitem',
            name='role',
            field=models.CharField(blank=True, choices=[('readme', 'Readme'), ('license', 'License'), ('rfc', 'Rfc'), ('w3c', 'W3C')], max_length=100, null=True),
        ),
    ]
