# Generated by Django 5.2.5 on 2025-11-17 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_documentationitem_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='schema',
            index=models.Index(fields=['published_at'], name='core_schema_publish_82ebcd_idx'),
        ),
    ]
