# Generated by Django 5.2.5 on 2025-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_documentationitem_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationitem',
            name='format',
            field=models.CharField(blank=True, choices=[('markdown', 'Markdown'), ('plaintext', 'Plaintext'), ('html', 'Html')], max_length=100, null=True),
        ),
    ]
