# Generated by Django 5.2.5 on 2025-11-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_documentationitem_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
