# Generated by Django 5.2.5 on 2025-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schema_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaref',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
