# Generated by Django 5.2.5 on 2025-12-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_schemaref_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationitem',
            name='format',
            field=models.CharField(blank=True, choices=[('markdown', 'Markdown'), ('plaintext', 'Plain text')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentationitem',
            name='role',
            field=models.CharField(blank=True, choices=[('readme', 'README'), ('license', 'License'), ('rfc', 'RFC'), ('w3c', 'W3C')], max_length=100, null=True),
        ),
    ]
