# Generated by Django 5.2.5 on 2026-03-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organization_description_organization_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='description',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
