# Generated by Django 5.2.5 on 2026-04-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_schema_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationitem',
            name='content_fetch_failing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='content_fetch_failing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemaref',
            name='content_fetch_failing_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
