# Generated by Django 5.2.5 on 2026-04-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaref',
            name='id_value',
            field=models.URLField(blank=True, null=True),
        ),
    ]
