from .base import *

DEBUG = True
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
PERMANENT_URL_HOST = "localhost"
SITE_URL = "http://localhost:8000"
ENABLE_MCP_SERVER = True

OAUTH2_PROVIDER["OIDC_ISS_ENDPOINT"] = SITE_URL
OAUTH2_PROVIDER["OAUTH2_PROTECTED_RESOURCE_IDENTIFIER"] = SITE_URL + "/mcp"
OAUTH2_PROVIDER["OAUTH2_PROTECTED_RESOURCE_AUTHORIZATION_SERVERS"] = [SITE_URL]
