from .base import *

PERMANENT_URL_HOST = "testserver"
ALLOWED_HOSTS = [PERMANENT_URL_HOST]
SITE_URL = f"http://{PERMANENT_URL_HOST}"
TRUSTED_CONTENT_DOMAINS.append("example.com")

OAUTH2_PROVIDER["OIDC_ISS_ENDPOINT"] = SITE_URL
OAUTH2_PROVIDER["OAUTH2_PROTECTED_RESOURCE_IDENTIFIER"] = SITE_URL + "/mcp"
OAUTH2_PROVIDER["OAUTH2_PROTECTED_RESOURCE_AUTHORIZATION_SERVERS"] = [SITE_URL]
